# rclone is a program to download data directly from cloud services
# use `rclone config` to set credentials etc
sync:
	rclone sync --drive-shared-with-me "drive:Carceral Ecologies--LAB SHARED/" drive
