# rclone is a program to download data directly from cloud services
# use `rclone config` to set credentials etc
sync:
	rclone sync --drive-shared-with-me "drive:Carceral Ecologies--LAB SHARED/" drive

wget:
	cd data && wget -nc https://echo.epa.gov/files/echodownloads/SDWA_downloads.zip
	cd data && wget -nc https://echo.epa.gov/files/echodownloads/SDWA_latest_downloads.zip
	cd data && wget -nc https://echo.epa.gov/files/echodownloads/npdes_downloads.zip
	cd data && wget -nc https://echo.epa.gov/files/echodownloads/case_downloads.zip
